name: Trigger auto deployment for dwittechinventoryservicewebapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dwittechinventoryservicewebapi-AutoDeployTrigger-e8e88320-83a7-43b5-8e86-f33612d1e5c5.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: dotnetcoreapi20230130123723.azurecr.io
          username: ${{ secrets.DWITTECHINVENTORYSERVICEWEBAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.DWITTECHINVENTORYSERVICEWEBAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dotnetcoreapi20230130123723.azurecr.io/dwittechinventoryservicewebapi:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DWITTECHINVENTORYSERVICEWEBAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n dwittechinventoryservicewebapi -g dwit-tech --server dotnetcoreapi20230130123723.azurecr.io --username  ${{ secrets.DWITTECHINVENTORYSERVICEWEBAPI_REGISTRY_USERNAME }} --password ${{ secrets.DWITTECHINVENTORYSERVICEWEBAPI_REGISTRY_PASSWORD }}
            az containerapp update -n dwittechinventoryservicewebapi -g dwit-tech --image dotnetcoreapi20230130123723.azurecr.io/dwittechinventoryservicewebapi:${{ github.sha }}
